# https://f1bonacc1.github.io/process-compose/
version: "0.5"

processes:
  backend:
    command: make backend/run
    depends_on:
      mysql:
        condition: "process_started"

  webapp:
    command: pnpm dev
    depends_on:
      backend:
        condition: "process_started"
    availability:
      restart: "always"

  mysql:
    command: |
      if [ ! -d "$MYSQL_DATA_DIR" ]; then
        mkdir $MYSQL_DATA_DIR
      fi
      if [ -z "$(ls -A $MYSQL_DATA_DIR)" ]; then
        mysqld --datadir=$MYSQL_DATA_DIR --initialize-insecure
      fi

      mysqld --socket=$MYSQL_UNIX_PORT --datadir=$MYSQL_DATA_DIR --port=$MYSQL_PORT --log-error=$MYSQL_HOME/mysql.log & MYSQL_PID=$! && echo 'Starting mysqld... check mysql_logs for details'
    is_daemon: true
    shutdown:
      command: "mysqladmin -u root shutdown"
    availability:
      restart: "always"
    depends_on:
      mysql_logs:
        condition: "process_started"
  mysql_logs:
    command: "tail -f $MYSQL_HOME/mysql.log"
    availability:
      restart: "always"
