package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"lxcard/backend/pkg/tenant"
)

// CardViewer represents a row from 'lxcard.card_viewers'.
type CardViewer struct {
	ID       string    `json:"id"`        // id
	TenantID tenant.ID `json:"tenant_id"` // tenant_id
	CardID   string    `json:"card_id"`   // card_id
	UserID   string    `json:"user_id"`   // user_id
}
