// Package db_model contains generated code for schema 'lxcard'.
package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"time"

	"lxcard/backend/pkg/tenant"
)

// Card represents a row from 'lxcard.cards'.
type Card struct {
	ID               string         `json:"id"`                 // id
	TenantID         tenant.ID      `json:"tenant_id"`          // tenant_id
	Name             string         `json:"name"`               // name
	OwnerID          string         `json:"owner_id"`           // owner_id
	State            State          `json:"state"`              // state
	LastFour         sql.NullString `json:"last_four"`          // last_four
	ExpirationMonth  sql.NullInt64  `json:"expiration_month"`   // expiration_month
	ExpirationYear   sql.NullInt64  `json:"expiration_year"`    // expiration_year
	Description      string         `json:"description"`        // description
	OnceMaxAmount    sql.NullInt64  `json:"once_max_amount"`    // once_max_amount
	MonthlyMaxAmount sql.NullInt64  `json:"monthly_max_amount"` // monthly_max_amount
	TotalMaxAmount   sql.NullInt64  `json:"total_max_amount"`   // total_max_amount
	StartDate        sql.NullTime   `json:"start_date"`         // start_date
	EndDate          sql.NullTime   `json:"end_date"`           // end_date
	ModifiedAt       time.Time      `json:"modified_at"`        // modified_at
}
