package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// CreateDiary represents a row from 'lxcard.create_diary'.
type CreateDiary struct {
	ID              string         `json:"id"`                // id
	EncryptionKeyID sql.NullString `json:"encryption_key_id"` // encryption_key_id
	UserID          string         `json:"user_id"`           // user_id
	SaveToBcAt      sql.NullTime   `json:"save_to_bc_at"`     // save_to_bc_at
	TokenID         sql.NullInt64  `json:"token_id"`          // token_id
	Content         string         `json:"content"`           // content
	Title           string         `json:"title"`             // title
}
