package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// CreateDiary represents a row from 'lxcard.create_diary'.
type CreateDiary struct {
	ID              string         `json:"id"`                // id
	EncryptionKeyID sql.NullString `json:"encryption_key_id"` // encryption_key_id
	Algo            sql.NullString `json:"algo"`              // algo
	UserID          string         `json:"user_id"`           // user_id
	DiaryID         string         `json:"diary_id"`          // diary_id
	SaveToBcAt      sql.NullTime   `json:"save_to_bc_at"`     // save_to_bc_at
}
