package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Diary represents a row from 'lxcard.diary'.
type Diary struct {
	ID      string        `json:"id"`       // id
	TokenID sql.NullInt64 `json:"token_id"` // token_id
	Content string        `json:"content"`  // content
	Title   string        `json:"title"`    // title
}
