package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"lxcard/backend/pkg/tenant"
)

// User represents a row from 'lxcard.users'.
type User struct {
	ID       string    `json:"id"`        // id
	TenantID tenant.ID `json:"tenant_id"` // tenant_id
	Name     string    `json:"name"`      // name
}
