// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateBdiaryUserInput struct {
	// ユーザのFirebase UID
	FirebaseUID string `json:"firebaseUid"`
	// ユーザのウォレットアドレス
	WalletAddress *string `json:"walletAddress,omitempty"`
}

type CreateBdiaryUserParams struct {
	// ユーザのFirebase UID
	FirebaseUID string `json:"firebaseUid"`
	// ユーザのウォレットアドレス
	WalletAddress *string `json:"walletAddress,omitempty"`
}

type CreateDiaryParams struct {
	// 日記内容
	Content string `json:"content"`
	// 日記のタイトル
	Title string `json:"title"`
	// ユーザーID
	UserID string `json:"userId"`
	// 日記の日付
	DiaryDate string `json:"diaryDate"`
}

type CreateUserDiaryInput struct {
	// 日記内容
	Content string `json:"content"`
	// 日記のタイトル
	Title string `json:"title"`
	// 日記作成者のFirebase UID
	FirebaseUID string `json:"firebaseUid"`
	// 日記作成者のウォレットアドレス
	WalletAddress *string `json:"walletAddress,omitempty"`
	// 日記の日付
	DiaryDate string `json:"diaryDate"`
}

type CreateUserInput struct {
	// ユーザ名
	Name string `json:"name"`
}

type DiariesInput struct {
	// 日記データ取得日時
	Date time.Time `json:"date"`
	// Firebase UID
	FirebaseUID string `json:"firebaseUid"`
}

type Diary struct {
	// 日記ID
	ID string `json:"id"`
	// 日記タイトル
	Title string `json:"title"`
	// 日記内容
	Content string `json:"content"`
	// 日記の日時
	DiaryDate string `json:"diaryDate"`
	// トークンID
	TokenID *uint `json:"tokenId,omitempty"`
	// 暗号化キー
	EncryptionKey *string `json:"encryptionKey,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateDiaryInput struct {
	// 日記ID
	ID string `json:"id"`
	// 日記内容
	Content string `json:"content"`
	// 日記のタイトル
	Title string `json:"title"`
}
